#server:
#  port: 8081
#spring:
#  servlet:      
#  datasource:
#    password: MAE2020
#    url: jdbc:postgresql://localhost:5432/rigo
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#  main:
#    allow-bean-definition-overriding: true
#    allow-circular-references: true    
#  profiles:
#    active: prod